# Connexion : DATABASE_URL (PostgreSQL en prod ; .env.local peut utiliser sqlite:// pour le dev sans Docker).
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
